name: Destroy infrastructure
on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
env:
  ARM_USE_AZUREAD: true
jobs:
  terraform_plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./infrastructure
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          cd ../environment 
          export KEYVAULT_NAME=$(jq '.keyvault_name' platform.json | tr -d \")
          echo "$KEYVAULT_NAME"
          export LOCATION=$(jq '.location' platform.json | tr -d \")
          echo "$LOCATION"
          export RESOURCE_GROUP_NAME=$(jq '.resource_group_name' platform.json | tr -d \")
          echo "$RESOURCE_GROUP_NAME"

      - name: Setup Terrform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt
        run: terraform fmt -check

      - name: Terrafor Init
        run: |
          terraform init \
          -backend-config="resource_group_name=${{secrets.BACKEND_RESOURCE_GROUP_NAME}}" \
          -backend-config="storage_account_name=${{secrets.BACKEND_STORAGE_ACCOUNT_NAME}}" \
          -backend-config="container_name=${{secrets.BACKEND_STORAGE_ACCOUNT_CONTAINER_NAME}}"

      - name: Terraform plan
        id: plan
        run: |
          terraform plan -destroy -var-file="../environment/dev.tfvars.json" -var="subscription_id=${{secrets.AZURE_SUBSCRIPTION_ID}}" -out=main.tfplan && terraform show main.tfplan

      - name: Publish Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: ./infrastructure/main.tfplan

  terraform_destroy:
    needs: terraform_plan
    name: Terraform Destroy
    runs-on: ubuntu-latest
    env:
      ARM_USE_AZUREAD: true
    defaults:
      run:
        shell: bash
        working-directory: ./infrastructure
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        id: init
        run: |
          terraform init \
          -backend-config="resource_group_name=${{secrets.BACKEND_RESOURCE_GROUP_NAME}}" \
          -backend-config="storage_account_name=${{secrets.BACKEND_STORAGE_ACCOUNT_NAME}}" \
          -backend-config="container_name=${{secrets.BACKEND_STORAGE_ACCOUNT_CONTAINER_NAME}}"

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: ./infrastructure

      - name: Terraform apply
        run: terraform apply -destroy -auto-approve "./main.tfplan"
